[build]
publish = "public"
command = "hugo --gc --minify --baseURL https://hopeful-hypatia-66a2d4.netlify.com"

[context.production.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
